// Autogenerated from Pigeon (v22.7.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Generated class from Pigeon that represents data sent in messages.
struct BluetoothScanResult {
  var deviceName: String
  var deviceAddress: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> BluetoothScanResult? {
    let deviceName = pigeonVar_list[0] as! String
    let deviceAddress = pigeonVar_list[1] as! String

    return BluetoothScanResult(
      deviceName: deviceName,
      deviceAddress: deviceAddress
    )
  }
  func toList() -> [Any?] {
    return [
      deviceName,
      deviceAddress,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ConnectionResult {
  var success: Bool
  var errorMessage: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ConnectionResult? {
    let success = pigeonVar_list[0] as! Bool
    let errorMessage: String? = nilOrValue(pigeonVar_list[1])

    return ConnectionResult(
      success: success,
      errorMessage: errorMessage
    )
  }
  func toList() -> [Any?] {
    return [
      success,
      errorMessage,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AccelerometerData {
  var x: Double
  var y: Double
  var z: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AccelerometerData? {
    let x = pigeonVar_list[0] as! Double
    let y = pigeonVar_list[1] as! Double
    let z = pigeonVar_list[2] as! Double

    return AccelerometerData(
      x: x,
      y: y,
      z: z
    )
  }
  func toList() -> [Any?] {
    return [
      x,
      y,
      z,
    ]
  }
}

private class ApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return BluetoothScanResult.fromList(self.readValue() as! [Any?])
    case 130:
      return ConnectionResult.fromList(self.readValue() as! [Any?])
    case 131:
      return AccelerometerData.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class ApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? BluetoothScanResult {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? ConnectionResult {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? AccelerometerData {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class ApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return ApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return ApiPigeonCodecWriter(data: data)
  }
}

class ApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = ApiPigeonCodec(readerWriter: ApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol BluetoothScannerApi {
  func startScanning(durationInMillis: Int64, completion: @escaping (Result<[BluetoothScanResult], Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class BluetoothScannerApiSetup {
  static var codec: FlutterStandardMessageCodec { ApiPigeonCodec.shared }
  /// Sets up an instance of `BluetoothScannerApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: BluetoothScannerApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let startScanningChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.seabattle.BluetoothScannerApi.startScanning\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startScanningChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let durationInMillisArg = args[0] as! Int64
        api.startScanning(durationInMillis: durationInMillisArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startScanningChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol BluetoothDeviceApi {
  func connect(deviceAddress: String, completion: @escaping (Result<ConnectionResult, Error>) -> Void)
  func disconnect(completion: @escaping (Result<Void, Error>) -> Void)
  func sendInt(value: Int64, completion: @escaping (Result<Bool, Error>) -> Void)
  func isConnected(completion: @escaping (Result<Bool, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class BluetoothDeviceApiSetup {
  static var codec: FlutterStandardMessageCodec { ApiPigeonCodec.shared }
  /// Sets up an instance of `BluetoothDeviceApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: BluetoothDeviceApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let connectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.seabattle.BluetoothDeviceApi.connect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      connectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let deviceAddressArg = args[0] as! String
        api.connect(deviceAddress: deviceAddressArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      connectChannel.setMessageHandler(nil)
    }
    let disconnectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.seabattle.BluetoothDeviceApi.disconnect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disconnectChannel.setMessageHandler { _, reply in
        api.disconnect { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      disconnectChannel.setMessageHandler(nil)
    }
    let sendIntChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.seabattle.BluetoothDeviceApi.sendInt\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendIntChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let valueArg = args[0] as! Int64
        api.sendInt(value: valueArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      sendIntChannel.setMessageHandler(nil)
    }
    let isConnectedChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.seabattle.BluetoothDeviceApi.isConnected\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      isConnectedChannel.setMessageHandler { _, reply in
        api.isConnected { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      isConnectedChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol BluetoothDataCallbackProtocol {
  func onStringReceived(value valueArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onConnectionStatusChanged(isConnected isConnectedArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void)
  func onError(errorMessage errorMessageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class BluetoothDataCallback: BluetoothDataCallbackProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: ApiPigeonCodec {
    return ApiPigeonCodec.shared
  }
  func onStringReceived(value valueArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.seabattle.BluetoothDataCallback.onStringReceived\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([valueArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onConnectionStatusChanged(isConnected isConnectedArg: Bool, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.seabattle.BluetoothDataCallback.onConnectionStatusChanged\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([isConnectedArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
  func onError(errorMessage errorMessageArg: String, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.seabattle.BluetoothDataCallback.onError\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([errorMessageArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol AccelerometerApi {
  func startAccelerometer(completion: @escaping (Result<Bool, Error>) -> Void)
  func stopAccelerometer(completion: @escaping (Result<Bool, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class AccelerometerApiSetup {
  static var codec: FlutterStandardMessageCodec { ApiPigeonCodec.shared }
  /// Sets up an instance of `AccelerometerApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: AccelerometerApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let startAccelerometerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.seabattle.AccelerometerApi.startAccelerometer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startAccelerometerChannel.setMessageHandler { _, reply in
        api.startAccelerometer { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      startAccelerometerChannel.setMessageHandler(nil)
    }
    let stopAccelerometerChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.seabattle.AccelerometerApi.stopAccelerometer\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopAccelerometerChannel.setMessageHandler { _, reply in
        api.stopAccelerometer { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopAccelerometerChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol AccelerometerDataCallbackProtocol {
  func onAccelerometerDataReceived(data dataArg: AccelerometerData, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class AccelerometerDataCallback: AccelerometerDataCallbackProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: ApiPigeonCodec {
    return ApiPigeonCodec.shared
  }
  func onAccelerometerDataReceived(data dataArg: AccelerometerData, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.seabattle.AccelerometerDataCallback.onAccelerometerDataReceived\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([dataArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
